DROP DATABASE IF EXISTS book_db;
CREATE DATABASE book_db;
USE book_db;

CREATE TABLE books
(
	ID INT NOT NULL AUTO_INCREMENT,
	titleAuth VARCHAR(200) NOT NULL,
	finished BOOLEAN DEFAULT false,
	PRIMARY KEY (ID)
);